syntax = "proto3";

package cmp.services.info.v3;

import "buf/validate/validate.proto";
import "cmp/types/v1/language.proto";
import "cmp/types/v1/travel_type.proto";
import "cmp/types/v2/country.proto";
import "cmp/types/v4/common.proto";
import "cmp/types/v4/datetime_range.proto";
import "cmp/types/v4/localized.proto";
import "cmp/types/v4/uuid.proto";
import "google/protobuf/timestamp.proto";

// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/info/v3/entry_requirements.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/info/v3/entry_requirements.proto.dot.svg)
//
/// @custom:cmp-service type:product routing:p2p on-chain:false structure:2
service CountryEntryRequirementsService {
  rpc CountryEntryRequirements(CountryEntryRequirementsRequest) returns (CountryEntryRequirementsResponse);
}

message CountryEntryRequirementsRequest {
  // Message header
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Departure country
  cmp.types.v2.Country departure = 2 [(buf.validate.field).enum = {
    defined_only: true // Only allow defined enum values
    not_in: [0] /* Exclude unspecified value */
  }];

  // Destination country
  cmp.types.v2.Country destination = 3 [(buf.validate.field).enum = {
    defined_only: true // Only allow defined enum values
    not_in: [0] /* Exclude unspecified value */
  }];

  // Citizenship
  cmp.types.v2.Country citizenship = 4 [(buf.validate.field).enum = {
    defined_only: true // Only allow defined enum values
    not_in: [0] /* Exclude unspecified value */
  }];

  // Residence
  cmp.types.v2.Country residence = 5 [(buf.validate.field).enum = {
    defined_only: true // Only allow defined enum values
    not_in: [0] /* Exclude unspecified value */
  }];

  // Transit country
  cmp.types.v2.Country transit = 6 [(buf.validate.field).enum = {
    defined_only: true // Only allow defined enum values, including UNSPECIFIED
  }];

  // Travel type, ex: business or tourism
  cmp.types.v1.TravelType travel_type = 7 [(buf.validate.field).enum = {
    defined_only: true // Only allow defined enum values, including UNSPECIFIED
  }];

  // Date time range, start and end dates of visit, as timestamp.
  cmp.types.v4.DateTimeRange datetime_range = 8 [(buf.validate.field).required = true];

  // Languages requested
  repeated cmp.types.v1.Language languages = 9 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
    unique: true
    items: {
      enum: {
        defined_only: true
        not_in: [0]
      }
    }
  }];

  // Flag to exclude categories (default: false)
  // This will prevent the list of `CountryEntryRequirementCategory`
  // from being included in the response.
  bool exclude_categories = 10;

  // Flag to include items (default: false)
  // This will include the list of `CountryEntryRequirementItem` in the response.
  bool include_items = 11;
}

message CountryEntryRequirementsSuccessResponse {
  // Message header
  cmp.types.v4.SuccessResponseHeader header = 1 [(buf.validate.field).required = true];

  // This must be a UUID according to RFC 4122
  cmp.types.v4.UUID response_id = 2 [(buf.validate.field).required = true];

  // Categories
  repeated cmp.services.info.v3.CountryEntryRequirementCategory categories = 3 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Items
  repeated cmp.services.info.v3.CountryEntryRequirementItem items = 4 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 10000
  }];
}

message CountryEntryRequirementsErrorResponse {
  // Common error response header used in every error response.
  cmp.types.v4.ErrorResponseHeader header = 1 [(buf.validate.field).required = true];
}

message CountryEntryRequirementsResponse {
  oneof response {
    option (buf.validate.oneof).required = true; // One must be provided
    cmp.services.info.v3.CountryEntryRequirementsSuccessResponse success_response = 1;
    cmp.services.info.v3.CountryEntryRequirementsErrorResponse error_response = 2;
  }
}

// Types

message CountryEntryRequirementCategory {
  // Category key.
  string key = 1 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];

  // List of localized names
  repeated cmp.types.v4.LocalizedString names = 2 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Items
  repeated cmp.services.info.v3.CountryEntryRequirementItem items = 3 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Sub categories
  repeated cmp.services.info.v3.CountryEntryRequirementCategory sub_categories = 4 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];
}

message CountryEntryRequirementItem {
  // Item type key.  FIXME: Can this field be an enum?
  string key = 1 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];

  // Language specific names and descriptions
  repeated cmp.services.info.v3.LocalizedItemInfo info = 2 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Status of the item. An item specifies an action or requirement which should be
  // done/provided or rather not. This is expressed with "true" and "false".
  // Examples:
  // Entry generally permitted, status=true
  // EU Digital COVID Certificate accepted, status=true
  // Visa required for stay, status=false
  // Entry forms required, status=false
  // Additional information, status=undefined
  cmp.services.info.v3.ItemStatus status = 3 [(buf.validate.field).enum = {defined_only: true}];

  // Significant update date
  //
  // Timestamps may be used for both off-chain and on-chain operations.
  // For on-chain operations, only seconds are supported, and nanoseconds
  // will be ignored.
  google.protobuf.Timestamp last_significant_update = 4;
}

message LocalizedItemInfo {
  string name = 1 [(buf.validate.field).string.max_bytes = 512];

  string description = 2 [(buf.validate.field).string.max_bytes = 512];

  cmp.types.v1.Language language = 3 [(buf.validate.field).enum = {
    defined_only: true // Only allow defined enum values
    not_in: [0] /* Exclude unspecified value */
  }];
}

// Status identifies whether an item should be done/provided or rather not. In case
// of an incident, there might be restrictions.
//
// UNKNOWN is different from UNSPECIFIED. For UNKNOWN information about this topic
// was sought, but it was not possible to find enough information to classify that
// topic
enum ItemStatus {
  ITEM_STATUS_UNSPECIFIED = 0;
  ITEM_STATUS_TRUE = 1;
  ITEM_STATUS_FALSE = 2;
  ITEM_STATUS_CRISIS = 3;
  ITEM_STATUS_RESTRICTIONS = 4;
  ITEM_STATUS_NO_RESTRICTIONS = 5;
  ITEM_STATUS_UNKNOWN = 6;
}
