syntax = "proto3";

package cmp.types.v4;

import "buf/validate/validate.proto";
import "cmp/types/v4/location.proto";

// This type represents an address for places like a home or hotel etc.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v2/address.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v2/address.proto.dot.svg)
message Address {
  string line_1 = 1 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];
  string line_2 = 2 [(buf.validate.field).string.max_bytes = 512];
  string district = 3 [(buf.validate.field).string.max_bytes = 512];
  string zip_code = 4 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];
  cmp.types.v4.GeoTree geo_tree = 5 [(buf.validate.field).required = true];
}

// TODO1: add rule to ALL strings as max 512 bytes
