syntax = "proto3";

package cmp.types.v4;

import "buf/validate/validate.proto";

// Amenity message type
//
// Examples:
//
// - Amenity message with a single attribute
//
// ```python
// Amenity(
//     type = AmenityType.AMENITY_TYPE_THEMES,
//     attributes = {
//         "theme": "Second-line beach hotel"
//     }
// )
// ```
//
// - Amenity message with multiple attributes
//
// ```python
// Amenity(
//     type = AmenityType.AMENITY_TYPE_INTERNET,
//     attributes = {
//         "lobby": "WiFi",
//         "charge": "extra fee",
//         "fee": "20",
//         "fee_unit": "EUR"
//     }
// )
// ```
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/amenity.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/amenity.proto.dot.svg)
// FIXME: Make this an enum to cover features and amenity types
// With the fields:
// * Type (enum AmenityType) - The type of amenity (e.g., INTERNET, POOL, FOOD_BEVERAGE, KITESURFING, GOLF COURSE, BALCONY, ROOM_SIZE, etc).
// * Value (int): The value associated with the amenity (e.g., speed in Mbps for INTERNET, size in square meters for ROOM_SIZE, etc).
// * Unit (enum): The unit of measurement for the value (e.g., "Mbps", "sqm", "km", "booking currency", "local currency", "count",  etc).
message Amenity {
  // Amenity type like INTERNET, POOL, FOOD_BEVERAGE
  cmp.types.v4.AmenityType type = 1 [(buf.validate.field).enum = {
    // Only allow defined types
    defined_only: true
    // Do not allow UNSPECIFIED
    not_in: [0]
  }];

  // Attributes of the amenity
  map<string, string> attributes = 2;
}

enum AmenityType {
  AMENITY_TYPE_UNSPECIFIED = 0;
  AMENITY_TYPE_FOOD_AND_DRINK = 1;
  AMENITY_TYPE_POOL = 2;
  AMENITY_TYPE_BEACH = 3;
  AMENITY_TYPE_ATTRACTIONS = 4;
  AMENITY_TYPE_THEMES = 5;
  AMENITY_TYPE_INTERNET = 6;
  AMENITY_TYPE_OTHER = 99;
}
