syntax = "proto3";

package cmp.types.v4;

import "buf/validate/validate.proto";
import "cmp/types/v4/time.proto";

// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/bookability.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/bookability.proto.dot.svg)
message Bookability {
  cmp.types.v4.BookabilityType type = 1 [(buf.validate.field).enum = {
    // Only allow defined types
    defined_only: true
    // Do not allow UNSPECIFIED
    not_in: [0]
  }];

  // In case of a bookable=on_request status, a confirmation time should be given by
  // the supplier. The supplier is to confirm the on-request booking with that
  // specified time. If confirmation id not provided, the booking is to be
  // considered "rejected".
  cmp.types.v4.Time confirmation_time = 2;

  option (buf.validate.message) = {
    // confirmation_time must NOT be present when AVAILABLE
    cel: {
      id: "bookability.no_confirmation_time_when_available"
      message: "confirmation_time must NOT be provided when bookable status is AVAILABLE"
      expression: "this.type == cmp.types.v4.BookabilityType.BOOKABILITY_TYPE_AVAILABLE ? !has(this.confirmation_time) : true"
    }

    // confirmation_time MUST be present when ON_REQUEST
    cel: {
      id: "bookability.confirmation_time_required_when_on_request"
      message: "confirmation_time must be provided when bookable status is ON_REQUEST"
      expression: "this.type == cmp.types.v4.BookabilityType.BOOKABILITY_TYPE_ON_REQUEST ? has(this.confirmation_time) : true"
    }
  };
}

enum BookabilityType {
  BOOKABILITY_TYPE_UNSPECIFIED = 0;
  BOOKABILITY_TYPE_AVAILABLE = 1;
  BOOKABILITY_TYPE_ON_REQUEST = 2;
}
