syntax = "proto3";

package cmp.types.v4;

import "buf/validate/validate.proto";
import "cmp/types/v4/contact_info.proto";

// Represents information about a company or organization.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/company.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/company.proto.dot.svg)
message Company {
  // The common or display name of the company.
  //
  // This is often the brand name or the name used in general communication.
  // Example: "Chain4Travel", "Acme Corp", "Global Airlines".
  string short_name = 1 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];

  // The official, registered legal name of the company.
  //
  // This name is used in legal documents, contracts, and official records. It may
  // include the legal structure suffix (e.g., AG, Ltd., Inc.). Example:
  // "Chain4Travel AG", "Acme Corporation Ltd.", "Global Airlines Inc.".
  string legal_name = 2 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];

  // Optional. Contact information associated with the company, such as address,
  // phone numbers, and email addresses.
  cmp.types.v4.ContactInfo contact_info = 3;
}
