syntax = "proto3";

package cmp.types.v4;

import "buf/validate/validate.proto";

// Date message that includes year, month and day as integers.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/date.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/date.proto.dot.svg)
message Date {
  uint32 year = 1 [(buf.validate.field).uint32 = {lte: 9999}];

  uint32 month = 2 [(buf.validate.field).uint32 = {
    gte: 1
    lte: 12
  }];

  uint32 day = 3 [(buf.validate.field).uint32 = {
    gte: 1
    lte: 31
  }];
}
