syntax = "proto3";

package cmp.types.v4;

import "buf/validate/validate.proto";
import "cmp/types/v1/language.proto";

// Localized description set for a given language
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/description.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/description.proto.dot.svg)
message LocalizedDescriptionSet {
  // Language
  cmp.types.v1.Language language = 1 [(buf.validate.field).enum = {
    defined_only: true
    not_in: [0]
  }];

  // Description set
  repeated cmp.types.v4.Description descriptions = 2 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
  }];
}

message Description {
  // Category of the description like "General", "Amenities".
  string category = 1 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];

  // Description text
  string text = 2 [(buf.validate.field).string = {
    min_len: 1
    max_len: 5000
  }];
}
