syntax = "proto3";

package cmp.types.v4;

import "buf/validate/validate.proto";

// Email type for general use.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/email.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v4/email.proto.dot.svg)
message Email {
  string address = 1 [(buf.validate.field).string.email = true];

  cmp.types.v4.EmailType type = 2 [(buf.validate.field).enum.defined_only = true];
}

// Email Types
enum EmailType {
  EMAIL_TYPE_UNSPECIFIED = 0;
  EMAIL_TYPE_RECEPTION = 1; // For services that require a reception like hotels, hostels, car rental.
  EMAIL_TYPE_BOOKING = 2; // For booking confirmations.
  EMAIL_TYPE_SUPPORT = 3; // General customer support.
  EMAIL_TYPE_INQUIRY_RESPONSE = 4; // Responses to customer inquiries.
  EMAIL_TYPE_TRANSPORT_INFO = 5; // Information regarding transport services.
  EMAIL_TYPE_CONFIRMATION = 6; // Confirmation email for on-request bookings.
  EMAIL_TYPE_FEEDBACK_REQUEST = 7; // Requests for customer feedback.
  EMAIL_TYPE_BILLING = 8; // Billing and payment related emails.
  EMAIL_TYPE_CANCELLATION = 9; // Cancellation notices.
  EMAIL_TYPE_REMINDER = 10; // Reminders for reservations or activities.
  EMAIL_TYPE_PROMOTIONAL = 11; // Promotional emails, offers, discounts.
  EMAIL_TYPE_UPDATES = 12; // Updates about services or policy changes.
  EMAIL_TYPE_ALERTS = 13; // Alerts or important notices.
  EMAIL_TYPE_NEWSLETTER = 14; // Regular newsletters.
}
