syntax = "proto3";

package cmp.types.v4;

import "buf/validate/validate.proto";
import "cmp/types/v4/date.proto";
import "cmp/types/v4/dow.proto";

// Travel Period
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v1/travel_period.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/types/v1/travel_period.proto.dot.svg)
message TravelPeriod {
  // Start date of a trip for messages where no Date/Time is required
  // (datetime_range.proto) when the travelling starts. Most trips will be for an
  // exact start and end date.
  cmp.types.v4.Date start_date = 1 [(buf.validate.field).required = true];

  // End date of a trip for messages where no Date/Time is required
  // (datetime_range.proto) when the travelling ends. The end date is different when
  // the trip is a one-way from point A to B compared to when the trip is a
  // fortnight holiday and the customers return home on the end date.
  cmp.types.v4.Date end_date = 2 [(buf.validate.field).required = true];

  // Setting the length of the trip in case of a flexible search. Flexible in this
  // context means that if "los" is provided the start_date and end_date is a range
  // that the los length should fit into.
  //
  // Ex: start date = 1 April, End date is 30 June, stay would be for 7 to 7 nights.
  //
  // Ex: start date = 1 April, End date is 30 June, stay would be for 7 to 10
  // nights.
  //
  // The arrival and departure must fall between start and end-date. If you exceed
  // this supplier might return an error.
  cmp.types.v4.LengthOfStay los = 3;

  // By adding a DayOfWeek restriction, the number of results can be reduced to the
  // specific arrival days in the interest of the end-customer who for example only
  // can travel during weekends or at the contrary desires to avoid the crowds by
  // travelling during weekdays.
  //
  // A bit mask is being used to express the DOW or DOWs.
  cmp.types.v4.DayOfWeek dow = 4;
}

// FIXME: Refine: Length of Stay is nights
message LengthOfStay {
  uint32 from = 1 [(buf.validate.field).uint32 = {gt: 0}];
  uint32 to = 2 [(buf.validate.field).uint32 = {gt: 0}];
  // FIXME: "to" must be greater than or equal to "from"
}
