syntax = "proto3";

package cmp.services.claim.v2;

import "buf/validate/validate.proto";
import "cmp/services/claim/v2/claim_types.proto";
import "cmp/types/v1/language.proto";
import "cmp/types/v4/common.proto";

message ClaimGetFormRequest {
  // Message header
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Languages to be included in the response for descriptions. Null means all
  // available languages.
  repeated cmp.types.v1.Language languages = 2 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Booking token ID for the policy. You get it after minting an Insurance policy. This is not the booking token of the trip.
  uint64 policy_token_id = 3;

  // TODO: If a form needs to be requested for a flight delay, cancellation, or baggage damage, is there a different reference
  // that should be used? For missing baggage, you likely have a report filed at the airport that includes a reference
  // (you can add the report itself later in the submit_claim_form message). Could this be a type of claim?
}

message ClaimGetFormResponse {
  // Message header
  cmp.types.v4.ResponseHeader header = 1 [(buf.validate.field).required = true];

  // Claim form
  cmp.services.claim.v2.ClaimForm form = 2;
}
