syntax = "proto3";

package cmp.services.claim.v2;

import "buf/validate/validate.proto";
import "cmp/services/claim/v2/claim_types.proto";
import "cmp/types/v4/common.proto";

// Request to submit extra info for a claim form
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/claim/v2/submit_claim_form_extra_info.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/claim/v2/submit_claim_form_extra_info.proto.dot.svg)
message ClaimSubmitFormExtraInfoRequest {
  // Message header
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Claim ID: Submission ID, Processing ID and Carrier ID
  cmp.services.claim.v2.ClaimId claim_id = 2;

  // Extra info needed
  repeated cmp.services.claim.v2.ClaimableService requested_info = 3 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];
}

message ClaimSubmitFormExtraInfoResponse {
  // Message header
  cmp.types.v4.ResponseHeader header = 1 [(buf.validate.field).required = true];

  // Claim Message Response to respond with claim ids (processing, carrier and submission) and message status
  cmp.services.claim.v2.ClaimMessageResponse claim_message_response = 2;

  // Claim Status
  cmp.services.claim.v2.ClaimStatus status = 3;
}
