syntax = "proto3";

package cmp.services.claim.v2;

import "buf/validate/validate.proto";
import "cmp/services/claim/v2/claim_types.proto";
import "cmp/types/v4/common.proto";

// Request to submit a claim form
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/claim/v2/submit_claim_form.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/claim/v2/submit_claim_form.proto.dot.svg)
message ClaimSubmitFormRequest {
  // Message header
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Claim form
  cmp.services.claim.v2.ClaimForm form = 2;
}

message ClaimSubmitFormSuccessResponse {
  // Message header
  cmp.types.v4.SuccessResponseHeader header = 1 [(buf.validate.field).required = true];

  // Claim Message Response to respond with claim ids (processing, carrier and submission) and message status
  cmp.services.claim.v2.ClaimMessageResponse claim_message_response = 2;

  // Claim Status
  cmp.services.claim.v2.ClaimStatus status = 3;
}

message ClaimSubmitFormErrorResponse {
  // Common error response header used in every error response.
  cmp.types.v4.ErrorResponseHeader header = 1 [(buf.validate.field).required = true];
}

message ClaimSubmitFormResponse {
  oneof response {
    option (buf.validate.oneof).required = true; // One must be provided
    cmp.services.claim.v2.ClaimSubmitFormSuccessResponse success_response = 1;
    cmp.services.claim.v2.ClaimSubmitFormErrorResponse error_response = 2;
  }
}
