syntax = "proto3";

package cmp.services.cancellation.v1;

import "cmp/types/v1/common.proto";

// Request for cancelling an active cancellation proposal
message CancelCancellationRequest {
  // Request header
  cmp.types.v1.RequestHeader header = 1;

  // Cancellation token ID
  uint64 token_id = 2;
}

// Response for cancelling an active cancellation proposal
message CancelCancellationResponse {
  // Response header
  cmp.types.v1.ResponseHeader header = 1;

  // Transaction ID on-chain for cancelling the cancellation proposal. This
  // transaction proves the cancellation of the cancellation proposal on-chain to
  // avoid disputes.
  string transaction_id = 2;
}
