syntax = "proto3";

package cmp.services.cancellation.v1;

import "cmp/types/v1/common.proto";
import "cmp/types/v3/evm_transaction.proto";
import "cmp/types/v3/price.proto";

// Request for countering a cancellation
message CounterCancellationRequest {
  // Request header
  cmp.types.v1.RequestHeader header = 1;

  // Cancellation token ID
  uint64 token_id = 2;

  // Refund amount to counter the cancellation proposal with
  cmp.types.v3.Price refund_amount = 3;
}

// Response for countering a cancellation
message CounterCancellationResponse {
  // Response header
  cmp.types.v1.ResponseHeader header = 1;

  // Transaction ID on-chain for the cancellation proposal counter.
  // This transaction can be verified on-chain to:
  // 1. Prove the exact time of the counter proposal
  // 2. Validate the counter refund amount
  // 3. Prevent disputes about counter terms
  cmp.types.v3.EVMTransactionID transaction_id = 2;
}
