syntax = "proto3";

package cmp.services.cancellation.v1;

import "cmp/services/cancellation/v1/reason.proto";
import "cmp/types/v1/common.proto";
import "cmp/types/v2/price.proto";

message InitiateCancellationRequest {
  // The request header
  cmp.types.v1.RequestHeader header = 1;

  // The token id of the booking to be cancelled
  uint64 token_id = 2;

  // The amount to be refunded
  cmp.types.v2.Price refund_amount = 3;

  // The cancellation reason
  cmp.services.cancellation.v1.CancellationReason reason = 4;
}

message InitiateCancellationResponse {
  // The response header
  cmp.types.v1.ResponseHeader header = 1;

  // Transaction ID on-chain for the cancellation proposal initiation. This
  // transaction proves the initiation of the cancellation proposal on-chain.
  //
  // This transaction can be verified on-chain to:
  // 1. Prove the exact time of initiation of the cancellation proposal
  // 2. Validate the refund amount
  // 3. Prevent disputes about the cancellation terms
  string transaction_id = 2;
}
