syntax = "proto3";

package cmp.services.cancellation.v1;

import "cmp/services/cancellation/v1/reason.proto";
import "cmp/types/v1/common.proto";
import "cmp/types/v3/evm_transaction.proto";
import "cmp/types/v3/price.proto";

// Request for initiation of a cancellation proposal
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/cancellation/v1/initiate.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/cancellation/v1/initiate.proto.dot.svg)
message InitiateCancellationRequest {
  // The request header
  cmp.types.v1.RequestHeader header = 1;

  // Booking token ID this request is for
  uint64 token_id = 2;

  // The amount to be refunded
  cmp.types.v3.Price refund_amount = 3;

  // The cancellation reason
  cmp.services.cancellation.v1.CancellationReason reason = 4;
}

message InitiateCancellationResponse {
  // The response header
  cmp.types.v1.ResponseHeader header = 1;

  // Transaction ID on-chain for the cancellation proposal initiation. This
  // transaction proves the initiation of the cancellation proposal on-chain.
  //
  // This transaction can be verified on-chain to:
  // 1. Prove the exact time of initiation of the cancellation proposal
  // 2. Validate the refund amount
  // 3. Prevent disputes about the cancellation terms
  cmp.types.v3.EVMTransactionID transaction_id = 2;
}
