syntax = "proto3";

package cmp.services.cancellation.v1;

enum CancellationRejectionReason {
  CANCELLATION_REJECTION_REASON_UNSPECIFIED = 0;
  CANCELLATION_REJECTION_REASON_TECHNICAL_ERROR = 1;
  CANCELLATION_REJECTION_REASON_INVALID_SERVICE_OR_BOOKING_REFERENCE = 2;
  CANCELLATION_REJECTION_REASON_BOOKING_IS_ALREADY_CANCELLED = 3;
  CANCELLATION_REJECTION_REASON_SERVICE_HAS_STARTED_OR_HAS_BEEN_DELIVERED = 4;
  CANCELLATION_REJECTION_REASON_CANCELLATION_WINDOW_EXPIRED = 5;
  CANCELLATION_REJECTION_REASON_SERVICE_CANNOT_BE_CANCELLED_ONLINE = 6;
  CANCELLATION_REJECTION_REASON_RATE_OR_FARE_CANNOT_BE_CANCELLED = 7;
  CANCELLATION_REJECTION_REASON_ENTIRE_PACKAGE_MUST_BE_CANCELLED = 8; // Service forms part of a package, the entire package must be cancelled
  CANCELLATION_REJECTION_REASON_REFUND_CURRENCY_NOT_SUPPORTED = 9;
}
