syntax = "proto3";

package cmp.services.cancellation.v1;

import "cmp/services/cancellation/v1/reason.proto";
import "cmp/types/v1/common.proto";

// Request for cancellation rejection
message RejectCancellationRequest {
  // Request Header
  cmp.types.v1.RequestHeader header = 1;

  // Token ID to reject the cancellation for (Booking Token)
  uint64 token_id = 2;

  // Reason for rejection
  cmp.services.cancellation.v1.RejectionReason reason = 3;
}

// Response for cancellation rejection
message RejectCancellationResponse {
  // Response Header
  cmp.types.v1.ResponseHeader header = 1;

  // Transaction ID on-chain for the cancellation proposal rejection. This
  // transaction proves the rejection of the proposal on-chain to avoid disputes.
  string transaction_id = 2;
}
