syntax = "proto3";

package cmp.services.cancellation.v1;

import "cmp/services/cancellation/v1/accept.proto";
import "cmp/services/cancellation/v1/accept_counter.proto";
import "cmp/services/cancellation/v1/cancel_proposal.proto";
import "cmp/services/cancellation/v1/counter.proto";
import "cmp/services/cancellation/v1/initiate.proto";
import "cmp/services/cancellation/v1/reject.proto";

// Cancellation service
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/cancellation/v1/services.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/cancellation/v1/services.proto.dot.svg)
service CancellationService {
  // Initiate cancellation
  rpc InitiateCancellation(InitiateCancellationRequest) returns (InitiateCancellationResponse) {}

  // Accept cancellation
  rpc AcceptCancellation(AcceptCancellationRequest) returns (AcceptCancellationResponse) {}

  // Reject cancellation
  rpc RejectCancellation(RejectCancellationRequest) returns (RejectCancellationResponse) {}

  // Counter cancellation
  rpc CounterCancellation(CounterCancellationRequest) returns (CounterCancellationResponse) {}

  // Accept countered cancellation
  rpc AcceptCounterCancellation(AcceptCounterCancellationRequest) returns (AcceptCounterCancellationResponse) {}

  // Cancel cancellation proposal
  rpc CancelCancellation(CancelCancellationRequest) returns (CancelCancellationResponse) {}
}
