syntax = "proto3";

package cmp.services.accommodation.v4;

import "buf/validate/validate.proto";
import "cmp/types/v4/airport.proto";
import "cmp/types/v4/amenity.proto";
import "cmp/types/v4/bed.proto";
import "cmp/types/v4/contact_info.proto";
import "cmp/types/v4/description.proto";
import "cmp/types/v4/file.proto";
import "cmp/types/v4/location.proto";
import "cmp/types/v4/meal_plan.proto";
import "cmp/types/v4/product_code.proto";
import "cmp/types/v4/product_status.proto";
import "cmp/types/v4/service_fact.proto";
import "cmp/types/v4/traveller.proto";
import "google/protobuf/timestamp.proto";

// Represents a basic set of property info for an accommodation product.
// This message is used to convey essential details about a property without
// including all the potentially extensive information found in the full
// property info message.
// Essentially it provides a summary of the most important details that are
// likely to be needed for initial decision-making whether this property shall
// be used by the distributor.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/accommodation/v4/property_types.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/accommodation/v4/property_types.proto.dot.svg)
message Property {
  // Timestamp of the last modification date of **any** of the property info.
  // This not only includes the fields which are part of this message but rather
  // if any information has been updated. It might also be that for instance
  // only images have been changed which are not part of this message.
  //
  // Timestamps may be used for both off-chain and on-chain operations.
  // For on-chain operations, only seconds are supported, and nanoseconds
  // will be ignored.
  google.protobuf.Timestamp last_modified = 1 [(buf.validate.field).required = true];

  // The supplier specific product code used to identify the property in every
  // context. This code is essential to link back to the the static data when
  // search results are received which only contain the supplier_code.
  cmp.types.v4.SupplierProductCode supplier_code = 2 [(buf.validate.field).required = true];

  // Additional product codes, which also identify the property but usually
  // from external mapping providers. Especially useful in the context of
  // receiving properties from different suppliers to identify whether
  // they are the same property as the supplier specific codes will be different.
  repeated cmp.types.v4.ProductCode product_codes = 3 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 500
  }];

  // The name of the property in the native language of the property location
  // Ex: "Beach Hotel Alanya"
  string name = 4 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];

  // Identifier of the property chain. Usually used for hotel chains.
  // Might be used by a distributor for instance to decide whether they want to
  // include specific chain hotels into their inventory.
  // Ex: "Hilton"
  string chain = 5 [(buf.validate.field).string.max_bytes = 512];

  // Certain properties can have a category rating. The officially obtained rating
  // should be used here.
  // Especially for hotels this is an indication of their quality and service level.
  // Please note that category ratings can vary between different regions and
  // Ex: CATEGORY_RATING_4_5
  cmp.services.accommodation.v4.CategoryRating category_rating = 6;

  // There are different rating systems for different types of properties.
  // This field is to define which rating system is being used for the
  // `category_rating` field.
  // Ex: CATEGORY_UNIT_PALMS
  cmp.services.accommodation.v4.CategoryUnit category_unit = 7;

  // Information about how to contact this property.
  cmp.types.v4.ContactInfo contact_info = 8 [(buf.validate.field).required = true];

  // Specific coordinates of this property. Not only useful to show this on a
  // map but also essential for searches based on geo-coordinates like geo-circle
  // or polygon searches.
  cmp.types.v4.Coordinates coordinates = 9 [(buf.validate.field).required = true];

  // The general status of this property. Only active properties can be taken
  // into account for further processing and will only be returned in search
  // results. Deactivated properties can be still included in the static data
  // but this state is reserved for properties which are about to be listed
  // or are about to be completely removed soon.
  cmp.types.v4.ProductStatus status = 10 [(buf.validate.field).required = true];

  // List of the airports in the vicinity of the property.
  // The list should only include airports which have a reasonable distance
  // and/or travel time to the property.
  // Usually the airports are used both as a filter criteria for the distributor
  // and to decide which flights / transfers to search for a specific property.
  // Ex: ["PMI", "ZRH", "AYT"]
  repeated cmp.types.v4.AirportCode airports = 11 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 10
  }];

  // If category_rating is provided, category_unit must also be provided
  option (buf.validate.message).cel = {
    id: "category_rating_unit_dependency"
    message: "If category_rating is provided, category_unit must also be provided"
    expression: "this.category_rating == cmp.services.accommodation.v4.CategoryRating.CATEGORY_RATING_UNSPECIFIED || this.category_unit != cmp.services.accommodation.v4.CategoryUnit.CATEGORY_UNIT_UNSPECIFIED"
  };

  // Property contact_info must have at least one address
  option (buf.validate.message).cel = {
    id: "contact_info_address_required"
    message: "Property contact_info must have at least one address"
    expression: "size(this.contact_info.addresses) > 0"
  };
}

enum CategoryRating {
  CATEGORY_RATING_UNSPECIFIED = 0;
  CATEGORY_RATING_0_5 = 1;
  CATEGORY_RATING_1_0 = 2;
  CATEGORY_RATING_1_5 = 3;
  CATEGORY_RATING_2_0 = 4;
  CATEGORY_RATING_2_5 = 5;
  CATEGORY_RATING_3_0 = 6;
  CATEGORY_RATING_3_5 = 7;
  CATEGORY_RATING_4_0 = 8;
  CATEGORY_RATING_4_5 = 9;
  CATEGORY_RATING_5_0 = 10;
  CATEGORY_RATING_5_5 = 11;
  CATEGORY_RATING_6_0 = 12;
  CATEGORY_RATING_6_5 = 13;
  CATEGORY_RATING_7_0 = 14;
  CATEGORY_RATING_7_5 = 15;
  CATEGORY_RATING_8_0 = 16;
  CATEGORY_RATING_8_5 = 17;
  CATEGORY_RATING_9_0 = 18;
  CATEGORY_RATING_9_5 = 19;
  CATEGORY_RATING_10_0 = 20;
}

enum CategoryUnit {
  CATEGORY_UNIT_UNSPECIFIED = 0;
  CATEGORY_UNIT_STARS = 1;
  CATEGORY_UNIT_PALMS = 2;
}

// Represents a more detailed set of property info for an accommodation product.
// This message is used to convey detailed information about a property without
// Essentially it provides every important detail for displaying the property
// to a customer.
// As this info can potentially become big depending on the property, it is
// intentionally split from the basic information found in the `Property` message
// to allow a process where this is only retrieved in case the distributor is
// actually interested in this level of detail.
message PropertyExtendedInfo {
  // Basic property information usually used for mapping / decision-making
  cmp.services.accommodation.v4.Property property = 1 [(buf.validate.field).required = true];

  // General images of the property. Please note that the room images shall not
  // be included here as they're part of the room information.
  repeated cmp.types.v4.Image images = 2 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // General videos of the property. Please note that the room videos shall not
  // be included here as they're part of the room information.
  repeated cmp.types.v4.Video videos = 3 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // A general classification of the property in various aspects.
  // Can be used by a distributor to better understand the property and its
  // intended target audience and to potentially provide filter options to
  // show (or exclude) certain types of properties.
  //
  // TODO: Improve (multiple enums like location type, guest type, etc)
  repeated string classifications = 4 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
    items: {
      string: {max_bytes: 512}
    }
  }];

  // General description of the property. Please note that room descriptions
  // shall not be included here as they're part of the room information.
  repeated cmp.types.v4.LocalizedDescriptionSet localized_descriptions = 5 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Payment type. Ex: "MERCHANT"
  //
  // TODO: Reevaluate & make this an enum if needed
  string payment_type = 6 [(buf.validate.field).string.max_bytes = 512];

  // Definition of the individual rooms (or room types).
  repeated cmp.services.accommodation.v4.Room rooms = 7 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
  }];
}

// Definition of a room (or room type). In case of Hotels this is usually
// a specific room type (e.g. "Deluxe Room", "Suite", etc.) while for
// holiday homes it describes the individual rooms which are part of the property
// like "Bed Room", "Living Room", "Kitchen", etc.
message Room {
  // Room code of the unit in case of hotel. Ex: "RMSDDB0000". This code must
  // explicitly match the supplier_room_code in the ProductList and the
  // ProductInfo messages, so that the static data like room  amenities,
  // descriptions, images etc. can be matched to the dynamic price and
  // availability data for display to the end user.
  // Even though it's unusual for holiday homes to have a unique identifier for
  // their rooms it's still needed in this context to be able to match the room
  // between search results and static data.
  string supplier_code = 1 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];

  // Room name. In case of hotel a standardized room name is often derived from
  // room code structures. Example: "superior sea view room".
  // For holiday homes we expect names like "Master Bedroom", "Second Bedroom" or
  // "Bathroom" when specific descriptions for each room are available.
  string supplier_name = 2 [(buf.validate.field).string.max_bytes = 512];

  // Original room name as assigned by the hotel. In case of specifically designated room
  // names by chains and both the chain and the customer wants to adhere to them.
  // Ex: "CEIBA CLUB", "CEIBA GOVERNORS SUITE", "GOVERNORS SUITE" or "ENCLAVE NATURE VIEW"
  // For hotel(chain) specific room names can be given for frequent guests
  // (i.e. Royale Governor Suite Oceanfront).
  // For holiday homes specific room names if available can be given.
  string original_name = 3 [(buf.validate.field).string.max_bytes = 512];

  // Similar to a property a room can (and should have) have individual images.
  repeated cmp.types.v4.Image images = 4 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // If there are videos available for the individual rooms they can be added here.
  repeated cmp.types.v4.Video videos = 5 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Description of the room for display purposes.
  repeated cmp.types.v4.LocalizedDescriptionSet descriptions = 6 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Possible meal plans for this room (also known as board codes).
  repeated cmp.types.v4.MealPlan meal_plans = 7 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // How many of which bed type are present in this room.
  repeated cmp.types.v4.Bed beds = 8 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // How many of which person types can occupy this room.
  // For holiday homes the individual bedrooms need to be considered. The
  // distributor then needs to sum up the individual room occupancies to
  // get the total occupancy of the holiday home.
  cmp.services.accommodation.v4.Occupancy total_occupancy = 9;

  // Definition of services which are possible for this room.
  // The actual offer may contain less services.
  repeated cmp.types.v4.ServiceFactDefinition services = 10 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Additional amenities which are possible for this room.
  repeated cmp.types.v4.Amenity amenities = 11 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];
}

// Occupancy definition of a room defining the constrains depending on the room type.
message Occupancy {
  // The minimum amount of guests which can occupy this room.
  // If `occupancy_options` are given this value must match the sum of the `min`
  // field of all options.
  // One exception to take into account is when `infant_counted_in_total_guests`
  // is true and infants are given in the `occupancy_options` field.
  uint32 min_guests = 1 [(buf.validate.field).uint32 = {gt: 0}];

  // The maximum amount of guests which can occupy this room.
  // If `occupancy_options` are given this value must match the sum of the `max`
  // field of all options.
  // One exception to take into account is when `infant_counted_in_total_guests`
  // is true and infants are given in the `occupancy_options` field.
  uint32 max_guests = 2 [(buf.validate.field).uint32 = {gt: 0}];

  // Flag to specify whether infants are counted in total guests or not
  bool infant_counted_in_total_guests = 3;

  // Individual occupancy options which when given must match with the constrains
  // of the occupancy. With this certain guest types and age ranges can be
  // defined for the guests. For more information see the message description.
  repeated cmp.services.accommodation.v4.OccupancyOption occupancy_options = 4 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Max guests must be greater than or equal to min guests
  option (buf.validate.message).cel = {
    id: "max_guests_gte_min_guests"
    message: "max_guests must be greater than or equal to min_guests"
    expression: "this.max_guests >= this.min_guests"
  };
}

// An occupancy option defines constrains based on specific guest types
// within a specific age range.
message OccupancyOption {
  // Guest type like adult, child, infant.
  cmp.types.v4.TravellerType guest_type = 1 [(buf.validate.field).enum = {
    defined_only: true
    not_in: [0]
  }];

  // Minimum amount of guests of the specified `guest_type`
  uint32 min = 2;

  // Maximum amount of guests of the specified `guest_type`
  uint32 max = 3 [(buf.validate.field).uint32 = {gt: 0}];

  // The minimum age of the specified `guest_type`
  uint32 min_age = 4;

  // The maximum age of the specified `guest_type`
  uint32 max_age = 5;

  // Max guests must be greater than or equal to min guests
  option (buf.validate.message).cel = {
    id: "max_guests_gte_min_guests"
    message: "max must be greater than or equal to min"
    expression: "this.max >= this.min"
  };

  // Max age must be greater than or equal to min age
  option (buf.validate.message).cel = {
    id: "max_age_gte_min_age"
    message: "max_age must be greater than or equal to min_age"
    expression: "this.max_age >= this.min_age"
  };

  // If guest_type is not ADULT, max_age must be greater than zero
  option (buf.validate.message).cel = {
    id: "max_age_required_for_non_adults"
    message: "If guest_type is not ADULT, max_age must be greater than zero"
    expression: "this.guest_type == cmp.types.v4.TravellerType.TRAVELLER_TYPE_ADULT || this.max_age > 0"
  };
}

// This message is used to specify the supplier codes and their status.
message PropertyShortListItem {
  // Supplier codes for the products that are modified after the timestamp in
  // `AccommodationProductShortListRequest`. The supplier codes can be used in
  // the `AccommodationProductListRequest` or in the `AccommodationProductInfoRequest`
  // for more or all details.
  cmp.types.v4.SupplierProductCode supplier_code = 1 [(buf.validate.field).required = true];

  // Status of the property. This is used when the "ShortList" or the "ProductList"
  // are pulled. New or modified products have "activated" and properties that are
  // no longer available from this supplier, will have the status "deactivated".
  // In case a property has the status "deactivated" no search results will be
  // returned for that property and a ProductInfo request might not return any
  // details.
  cmp.types.v4.ProductStatus status = 2 [(buf.validate.field).enum = {
    defined_only: true
    not_in: [0]
  }];
}
