syntax = "proto3";

package cmp.services.accommodation.v4;

import "buf/validate/validate.proto";
import "cmp/types/v4/location.proto";
import "cmp/types/v4/meal_plan.proto";
import "cmp/types/v4/product_code.proto";
import "cmp/types/v4/rate.proto";

// This type is used in search requests for parameters like location, meal plan
// codes etc.
//
// ## Supplier-Specific Requirements
// While all fields in this message are optional at the message level, each supplier
// may define their own minimum set of required filter parameters.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/accommodation/v2/search_parameters_types.proto.dot.xs.svg)
//
// [Open Message
// Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/accommodation/v2/search_parameters_types.proto.dot.svg)
message AccommodationSearchParameters {
  // The geo location used for the search.
  oneof geo_location {
    // A list of location codes or just one code.
    cmp.types.v4.LocationCodes location_codes = 1;

    // Single geographic point represented by two double fields.
    cmp.types.v4.Coordinates location_coordinates = 2;

    // Geo tree type, represented by Country, Region, and City_or_Resort.
    cmp.types.v4.GeoTree location_geo_tree = 3;

    // Geo circle. Represented by a coordinate and a distance for radius
    cmp.types.v4.GeoCircle location_geo_circle = 4;

    // Geo polygon. Represented by a list of coordinate points.
    cmp.types.v4.GeoPolygon location_geo_polygon = 5;
  }

  // Meal plans for rooms (also known as board codes).
  // Specified in the room static data `Room.meal_plans`
  repeated cmp.types.v4.MealPlan meal_plan_codes = 6 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Rate plans and their meaning are often exchanged once partners initiate
  // a collaboration. These codes are sporadically updated/amended and are usually
  // (treated as) unique for the supplier.
  repeated cmp.types.v4.RatePlan rate_plans = 7 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // For rate rules the same applies as for `rate_plans`. This is something which
  // needs to be synchronized by the involved parties.
  repeated cmp.types.v4.RateRule rate_rules = 8 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // A list of product codes as defined in the static data.
  // See `Property.product_codes`
  repeated cmp.types.v4.ProductCode product_codes = 9 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 500
  }];

  // A list of supplier specific product codes as defined in the static data.
  // See `Property.supplier_code`
  repeated cmp.types.v4.SupplierProductCode supplier_codes = 10 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 500
  }];
}
