syntax = "proto3";

package cmp.services.accommodation.v4;

import "buf/validate/validate.proto";
import "cmp/services/accommodation/v4/search_parameters_types.proto";
import "cmp/services/accommodation/v4/unit_types.proto";
import "cmp/types/v4/travel_period.proto";
import "cmp/types/v4/traveller.proto";

// Represents a search query for accommodations.
// Please note that multiple of these can be given in a single request and must
// be treated completely individual.
message AccommodationSearchQuery {
  // Integer query ID. This must be unique per search request.
  uint32 query_id = 1;

  // Accommodation specific search parameters Ex: Specific search parameters like
  // geo location, meal plan, rate plan and rate rules.
  //
  // While all fields in accommodation search parameters message are optional at the
  // message level, each supplier may define their own minimum set of required
  // filter parameters.
  cmp.services.accommodation.v4.AccommodationSearchParameters search_parameters_accommodation = 2;

  // The intended travel period to search for. Please note that this refers
  // to the actual start and end times of the stay in the property and does not
  // include potential travel times for transfer/transportation.
  cmp.types.v4.TravelPeriod travel_period = 3 [(buf.validate.field).required = true];

  // Definition of the travellers to match against the occupancy definitions
  // of the properties.
  repeated cmp.types.v4.BasicTraveller travellers = 4 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 15
  }];

  // TODO: Unit count and type may not be needed here. Needs refinement. FIXME: before v12
  // - Unit count should be removed because it creates multiple ways of defining multi-room request
  // - Unit type should be removed because it makes it possible to query room and holiday homes in the same search request

  // Total number of rooms / holiday homes
  uint32 unit_count = 5;

  // Type of the unit, like room or holiday home
  cmp.services.accommodation.v4.UnitType unit_type = 6 [(buf.validate.field).enum = {
    defined_only: true
    not_in: [0]
  }];
}
