syntax = "proto3";

package cmp.services.accommodation.v4;

import "buf/validate/validate.proto";
import "cmp/services/accommodation/v4/search_parameters_types.proto";
import "cmp/services/accommodation/v4/unit_types.proto";
import "cmp/types/v4/travel_period.proto";
import "cmp/types/v4/traveller.proto";

message AccommodationSearchQuery {
  // Integer query ID, unique per search request
  int32 query_id = 1 [(buf.validate.field).int32 = {gte: 0}];

  // Accommodation specific search parameters Ex: Specific search parameters like
  // geo location, meal plan, rate plan and rate rules.
  cmp.services.accommodation.v4.AccommodationSearchParameters search_parameters_accommodation = 2;

  // Travel period
  cmp.types.v4.TravelPeriod travel_period = 3;

  // Travellers
  repeated cmp.types.v4.BasicTraveller travellers = 4 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 15
  }];

  // Total number of rooms / holiday homes
  int32 unit_count = 5 [(buf.validate.field).int32 = {gte: 0}];

  // Type of the unit, like room or holiday home
  cmp.services.accommodation.v4.UnitType unit_type = 6;
}
