syntax = "proto3";

package cmp.services.accommodation.v4;

import "buf/validate/validate.proto";
import "cmp/services/accommodation/v4/property_types.proto";
import "cmp/types/v4/common.proto";
import "google/protobuf/timestamp.proto";

// Request a list of modified accommodations.
message AccommodationProductShortListRequest {
  // Common request header used in every request.
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Only respond with the products that are modified after this timestamp
  //
  // The "modified_after" parameter is used to identify updated products from
  // Suppliers.
  google.protobuf.Timestamp modified_after = 2;
}

message AccommodationProductShortListSuccessResponse {
  // Common response header used in every successful response.
  cmp.types.v4.SuccessResponseHeader header = 1 [(buf.validate.field).required = true];

  // Supplier codes and status for the products that are modified after the timestamp
  // in the `AccommodationProductShortListRequest`. If there are no changes, the list
  // will be empty.
  repeated cmp.services.accommodation.v4.PropertyShortListItem property_short_list_items = 2;
}

message AccommodationProductShortListErrorResponse {
  // Common error response header used in every error response.
  cmp.types.v4.ErrorResponseHeader header = 1 [(buf.validate.field).required = true];
}

// Respond a list of modified accommodations.
message AccommodationProductShortListResponse {
  oneof response {
    option (buf.validate.oneof).required = true; // One must be provided
    cmp.services.accommodation.v4.AccommodationProductShortListSuccessResponse success_response = 1;
    cmp.services.accommodation.v4.AccommodationProductShortListErrorResponse error_response = 2;
  }
}

// Accommodation product short list service definition. This is an alternative
// to `AccommodationProductListService`.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/accommodation/v4/short_list.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/accommodation/v4/short_list.proto.dot.svg)
//
/// @custom:cmp-service type:product routing:p2p on-chain:false structure:2
service AccommodationProductShortListService {
  // Returns product list for accommodation (properties) with only supplier codes.
  // This can then be used to identify new or updated properties for mapping purposes.
  rpc AccommodationProductShortList(AccommodationProductShortListRequest) returns (AccommodationProductShortListResponse);
}
