syntax = "proto3";

package cmp.services.cancellation.v2;

import "buf/validate/validate.proto";
import "cmp/services/cancellation/v1/reason.proto";
import "cmp/types/v4/common.proto";
import "cmp/types/v4/evm_transaction.proto";
import "cmp/types/v4/price.proto";

// Request for countering a cancellation
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/cancellation/v2/counter.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/cancellation/v2/counter.proto.dot.svg)
message CounterCancellationRequest {
  // Request header
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Booking token ID this request is for
  uint64 token_id = 2;

  // Refund amount to counter the cancellation proposal with
  cmp.types.v4.Price refund_amount = 3 [(buf.validate.field).required = true];

  // Counter reason
  cmp.services.cancellation.v1.CounterReason reason = 4 [(buf.validate.field).enum = {
    defined_only: true // Only allow defined enum values
    not_in: [0] /* Exclude unspecified value */
  }];
}

// Response for countering a cancellation
message CounterCancellationSuccessResponse {
  // Response header
  cmp.types.v4.SuccessResponseHeader header = 1 [(buf.validate.field).required = true];

  // Transaction ID on-chain for the cancellation proposal counter.
  // This transaction can be verified on-chain to:
  // 1. Prove the exact time of the counter proposal
  // 2. Validate the counter refund amount
  // 3. Prevent disputes about counter terms
  cmp.types.v4.EVMTransactionID transaction_id = 2 [(buf.validate.field).required = true];
}

message CounterCancellationErrorResponse {
  // Common error response header used in every error response.
  cmp.types.v4.ErrorResponseHeader header = 1 [(buf.validate.field).required = true];
}

message CounterCancellationResponse {
  oneof response {
    option (buf.validate.oneof).required = true; // One must be provided
    cmp.services.cancellation.v2.CounterCancellationSuccessResponse success_response = 1;
    cmp.services.cancellation.v2.CounterCancellationErrorResponse error_response = 2;
  }
}
