syntax = "proto3";

package cmp.services.cancellation.v2;

import "buf/validate/validate.proto";
import "cmp/types/v4/common.proto";
import "cmp/types/v4/evm_transaction.proto";
import "cmp/types/v4/price.proto";

// Request for finalization of a cancellation proposal
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/cancellation/v2/finalize.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/cancellation/v2/finalize.proto.dot.svg)
message FinalizeCancellationRequest {
  // The request header
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Booking token ID this request is for
  uint64 token_id = 2;

  // The amount to be refunded
  cmp.types.v4.Price refund_amount = 3 [(buf.validate.field).required = true];
}

message FinalizeCancellationResponse {
  // The response header
  cmp.types.v4.ResponseHeader header = 1 [(buf.validate.field).required = true];

  // Transaction ID on-chain for the cancellation proposal finalization. This
  // transaction proves the finalization of the cancellation proposal on-chain.
  //
  // This transaction can be verified on-chain to:
  // 1. Prove the exact time of finalization of the cancellation proposal
  // 2. Validate the refund amount
  // 3. Prevent disputes about the cancellation terms
  cmp.types.v4.EVMTransactionID transaction_id = 2 [(buf.validate.field).required = true];
}
