syntax = "proto3";

package cmp.services.activity.v4;

import "buf/validate/validate.proto";
import "cmp/types/v4/common.proto";
import "cmp/types/v4/product_code.proto";
import "google/protobuf/timestamp.proto";

message ActivityProductListRequest {
  // Message header
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Only respond with the products that are modified after this timestamp
  //
  // Timestamps may be used for both off-chain and on-chain operations.
  // For on-chain operations, only seconds are supported, and nanoseconds
  // will be ignored.
  google.protobuf.Timestamp modified_after = 2;
}

message ActivityProductListResponse {
  // Message header
  cmp.types.v4.ResponseHeader header = 1 [(buf.validate.field).required = true];

  // List of supplier codes of activities
  repeated cmp.types.v4.SupplierProductCode supplier_codes = 2;
}

// This service is used to get a product list for activities.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/activity/v3/list.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/activity/v3/list.proto.dot.svg)
//
/// @custom:cmp-service type:product routing:p2p on-chain:false
service ActivityProductListService {
  // Gets an optional `modified_after` date and returns a product list.
  rpc ActivityProductList(ActivityProductListRequest) returns (ActivityProductListResponse);
}
