syntax = "proto3";

package cmp.services.seat_map.v4;

import "buf/validate/validate.proto";
import "cmp/types/v1/language.proto";
import "cmp/types/v4/common.proto";
import "cmp/types/v4/seat_map.proto";

// Request for seat map data
//
// Requests the seat map data for a given map ID
message SeatMapRequest {
  // Request header
  //
  // Header contains information about the request
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Unique identifier for the seat map
  //
  // This is the map ID that is received in the search results and also from the
  // product info responses.
  cmp.types.v4.SeatMapID map_id = 2 [(buf.validate.field).required = true];

  // Requested Languages
  repeated cmp.types.v1.Language languages = 3 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
    unique: true
    items: {
      enum: {
        defined_only: true
        not_in: [0]
      }
    }
  }];
}

message SeatMapSuccessResponse {
  // Response header
  //
  // Header contains information about the response
  cmp.types.v4.SuccessResponseHeader header = 1 [(buf.validate.field).required = true];

  // Seat map data
  //
  // Contains the seat map data for the requested map ID
  cmp.types.v4.SeatMap seat_map = 2;
}

message SeatMapErrorResponse {
  // Common error response header used in every error response.
  cmp.types.v4.ErrorResponseHeader header = 1 [(buf.validate.field).required = true];
}

// Response for seat map request
//
// Contains the seat map data for a given map ID
message SeatMapResponse {
  oneof response {
    option (buf.validate.oneof).required = true; // One must be provided
    cmp.services.seat_map.v4.SeatMapSuccessResponse success_response = 1;
    cmp.services.seat_map.v4.SeatMapErrorResponse error_response = 2;
  }
}

// Service for requesting seat map data for a given map ID
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/seat_map/v4/seat_map.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/seat_map/v4/seat_map.proto.dot.svg)
//
/// @custom:cmp-service type:product routing:p2p on-chain:false
service SeatMapService {
  // Get seat map data
  //
  // Requests the seat map data for a given map ID
  rpc SeatMap(SeatMapRequest) returns (SeatMapResponse);
}
