syntax = "proto3";

package cmp.services.transport.v4;

import "buf/validate/validate.proto";
import "cmp/services/transport/v4/trip_types.proto";
import "cmp/types/v4/bookability.proto";
import "cmp/types/v4/cancel_policy.proto";
import "cmp/types/v4/change_policy.proto";
import "cmp/types/v4/datetime_range.proto";
import "cmp/types/v4/link.proto";
import "cmp/types/v4/price.proto";
import "cmp/types/v4/rate.proto";

// Transport search result
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/transport/v3/search_result_types.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/transport/v3/search_result_types.proto.dot.svg)
message TransportSearchResult {
  // Unique result ID
  uint32 result_id = 1;

  // Query ID is the id of the query this result is generated for
  uint32 query_id = 2;

  // Offer ID.
  //
  // Option to carry through an offer identifier for other stateful provider systems
  // like NDC AirShopping RS
  string offer_id = 3 [(buf.validate.field).string.max_bytes = 512];

  // Travellers
  repeated uint32 traveller_ids = 4 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
  }];

  // Travelling trip. A travelling trip can be repeated and will be in many cases 2
  // trips: an outbound and returning trip from and to the same destination.
  // However, it is very much possible to specify your trip around the world into
  // several "Trips". For example AMS-NYC and after a couple of days NYC-IAH. There
  // we rent a car and do a road trip to San Fransisco and we take a flight from SFO
  // to SYD, where afer a couple of days we move on to Indonesia, Thailand, Japan,
  // Türkiye and back to Amsterdam again.
  repeated cmp.services.transport.v4.TripExtended travelling_trips = 5 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
  }];

  // Represents the complete pricing information for a product or service, including
  // both the total price value and an optional breakdown of price components.
  cmp.types.v4.TotalPrice total_price = 6 [(buf.validate.field).required = true];

  // Rate Rules
  repeated cmp.types.v4.RateRule rate_rules = 7 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Links
  // FIXME: Clarify why this is needed?
  repeated cmp.types.v4.Link links = 8 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Status of the result, whether it is immediately bookable or not
  cmp.types.v4.Bookability bookability = 9 [(buf.validate.field).required = true];

  // FIXME: Do we also need validity (below) in accommodation/activity?

  // Validity of the search option.
  //
  // `DateTimeRange` type with `start_date` and `end_date` in which the option can
  // be booked. If the start_date is omitted, the offer can be booked until the
  // end-date.
  //
  // FIXME: Clarify if datetime range is needed here or just a end_date timestamp is sufficient!
  cmp.types.v4.DateTimeRange validity = 10 [(buf.validate.field).required = true];

  // Cancel Policy
  cmp.types.v4.CancelPolicy cancel_policy = 11 [(buf.validate.field).required = true];

  // Change Policy
  cmp.types.v4.ChangePolicy change_policy = 12;

  // Observations
  // FIXME: Clarify what this is used for?
  string observations = 13 [(buf.validate.field).string.max_bytes = 512];
}
