syntax = "proto3";

package cmp.services.transport.v4;

import "buf/validate/validate.proto";
import "cmp/types/v4/baggage.proto";
import "cmp/types/v4/duration.proto";
import "cmp/types/v4/location.proto";
import "cmp/types/v4/measurement.proto";
import "cmp/types/v4/price.proto";
import "cmp/types/v4/product_code.proto";
import "cmp/types/v4/seat_map.proto";
import "cmp/types/v4/service_fact.proto";
import "google/protobuf/timestamp.proto";

// This message type represents a one way trip, either travelling or returning.
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/transport/v4/trip_types.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/transport/v4/trip_types.proto.dot.svg)
message TripExtended {
  // Trip supplier code
  cmp.types.v4.SupplierProductCode supplier_code = 1 [(buf.validate.field).required = true];

  // Luggage
  //
  // Ex: `3`
  cmp.types.v4.Baggage baggage = 2;

  // Price
  //
  // Ex: `Price(net=240, currency=Currency.CURRENCY_EUR)
  cmp.types.v4.Price price = 3 [(buf.validate.field).required = true];

  // Trip segments are the legs offered. Here we use extended segments type.
  //
  // Departure and Arrival dates and times can be derived from the first and last segments
  repeated cmp.services.transport.v4.SegmentExtended segments = 4 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
  }];
}

// A whole trip from the first segment till the last one with basic information.
//
// Intended to be used in list service.
message TripBasic {
  // Trip supplier code
  cmp.types.v4.SupplierProductCode supplier_code = 1 [(buf.validate.field).required = true];

  // Trip segments are the legs offered
  //
  // Departure and Arrival dates and times can be derived from the first and last segments
  repeated cmp.services.transport.v4.Segment segments = 2 [(buf.validate.field).repeated = {
    min_items: 1
    max_items: 100
  }];

  // Timestamps may be used for both off-chain and on-chain operations.
  // For on-chain operations, only seconds are supported, and nanoseconds
  // will be ignored.
  google.protobuf.Timestamp last_modified = 3 [(buf.validate.field).required = true];
}

// Extended information about the segment in the search data where additional
// fields are included to express the differences of the search results.
// This is referencing a unique `id` (= Segment.id from the static data)
// to provide the necessary context for the search results.
message SegmentExtended {
  // The unique segment ID received via the product list response. See Segment.id
  // Ex: "SEG1234"
  string id = 1 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];

  // Flights, trains and transfers often offer different service types
  // for a product. Think about economy or business for flights, first and second
  // class on trains and a shared shuttle or a private transfer.
  //
  // Service type code examples:
  // flight: "Y", "J", "F".
  // train: "1st", "2nd" or "S", "C", "P"
  // transfer: "S", "P", "VIP", "SS"
  // bus: no formal codes are known at the moment
  string service_type_code = 2 [(buf.validate.field).string.max_bytes = 512];

  // Service type description examples:
  // flight: "Economy Class", "Business Class", "First Class"
  // train: "First Class", "Second Class" or "standard", "comfort", and "premium",..
  // transfer: "Shuttle", "Private", "VIP Limosine", "Speedy Shuttle",...
  // bus: Classic, Panorama, Front, Table, Comfort, Extra, Single, Semi-bed, Bed
  string service_type_description = 3 [(buf.validate.field).string.max_bytes = 512];

  // Included, optional or compulsory services for this segment or leg. Just a code and
  // description can be included if it is a package (seat, priority, large carry-on).
  // or a price detail can be included for optionally pre-ordered meals for example.
  repeated cmp.types.v4.ServiceFact services = 4 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // Minimum number of passengers required for this segment to operate
  //
  // Ex: `1`
  uint32 min_pax = 5;

  // Maximum number of passengers that can be accommodated on this segment
  //
  // Ex: `3`
  uint32 max_pax = 6;

  // If this segment has a seat_map_id return the one in the context of this
  // search result. This can then be used to request seat map availabilities.
  // The seat_map_id must match one of the defined in the static data.
  // See Segment.seat_map_ids
  cmp.types.v4.SeatMapID seat_map_id = 7;
}

// Base definition of a segment for the static data (ProductInfo)
// This info is referenced in the search results via the
// SegmentExtended.id = Segment.id field.
message Segment {
  // Unique identifier of this segment used as a reference from the search results
  // to this static data definition of the segment.
  // Ex: "SEG1234"
  string id = 1 [(buf.validate.field).string = {
    min_len: 1
    max_bytes: 512
  }];

  // Operator Code in case the supplier has sub-contracted services.
  //
  // Ex: "EW" for Eurowings in case of a flight. DB for Deutsche Bahn
  // in case of train. HT for Holiday Taxi or MTS for MTS in case of a transfer.
  string operator_code = 2 [(buf.validate.field).string.max_bytes = 512];

  // Retailer Code, replacing Marketing carrier The example would be where Iberia is
  // selling an Iberia Express flight. So in this example the retailer_code for
  // Iberia would be "IB" and the operator_code for Iberia Express would be "I2".
  // Similar "interline" or "code share" operation may exist in rail and transfer.
  string retailer_code = 3 [(buf.validate.field).string.max_bytes = 512];

  // Sub supplier code, replacing Operating carrier or identifying sub contracted
  // services provided by other suppliers.
  //
  // DB could be selling an international train trip operated by the Dutch Nederlands
  // Spoorwegen (NS) or the French SNCF. Holiday Taxis could be selling a transfer
  // that is operated by Transunion.
  string sub_supplier_code = 4 [(buf.validate.field).string.max_bytes = 512];

  // For products which are globally identified by external providers like IATA,
  // ICAO for flights, or other global identification systems the product_code
  // is used. In case the product is only identified by a supplier specific code,
  // the supplier_code field is used.
  oneof product_identifier {
    option (buf.validate.oneof).required = true; // One must be provided
    // Product Code and Number
    //
    // For flights we use the IATA or ICAO airline code in the code field and the
    // flight number in the number field.
    //
    // For train some operators use a combination of a code and a number like
    // Eurostar, but others just use a code or a number (SNCF).
    //
    // Transfers are often identified by just a product code servicing an area.
    cmp.types.v4.ProductCode product_code = 5;

    // Supplier specific code, matching the supplier code in ProductListResponse
    cmp.types.v4.SupplierProductCode supplier_code = 6;
  }

  // Departure of this segment (sometimes also called origin)
  cmp.services.transport.v4.TransitEvent departure = 7 [(buf.validate.field).required = true];

  // Arrival of this segment (sometimes also called destination)
  cmp.services.transport.v4.TransitEvent arrival = 8 [(buf.validate.field).required = true];

  // The duration of this segment from departure to arrival
  cmp.types.v4.Duration duration = 9;

  // The distance of this segment from departure to arrival
  // Ex: `Length(value=15, unit=LengthUnit.DISTANCE_UNIT_KILOMETERS)`
  cmp.types.v4.Length distance = 10;

  // Definition of all static data connected to services which can be part
  // of this segment in the search response.
  repeated cmp.types.v4.ServiceFactDefinition services = 11 [(buf.validate.field).repeated = {
    min_items: 0
    max_items: 100
  }];

  // In case this segment has a seat maps defined, refer to the correct map_ids,
  // so that a SeatMap request can be made. (See SeatMap.id)
  // The field is repeated because the same segment can have a multitude of
  // different seat maps when different airplanes or busses are used.
  // This enables distributors to get the seat maps prior to a search to cache
  // them for only requesting seat map availabilities after each search.
  // The seat map id for the offer when doing a search will then be
  // one of the seat_map_ids values defined here.
  repeated cmp.types.v4.SeatMapID seat_map_ids = 12;

  // Specifies the type of transport for this segment
  // Ex: `TransportType.TRANSPORT_TYPE_FLIGHT`
  cmp.services.transport.v4.TransportType transport_type = 13 [(buf.validate.field).enum = {
    defined_only: true
    not_in: [0]
  }];
}

// Represents a departure or arrival event
message TransitEvent {
  // Date time of the event
  //
  // Timestamps may be used for both off-chain and on-chain operations.
  // For on-chain operations, only seconds are supported, and nanoseconds
  // will be ignored.
  google.protobuf.Timestamp date_time = 1 [(buf.validate.field).required = true];

  // Physical location where this departure or arrival event occurs
  cmp.services.transport.v4.TransitEventLocation location = 2 [(buf.validate.field).required = true];
}

// Represents a departure or arrival event's location
message TransitEventLocation {
  oneof location {
    option (buf.validate.oneof).required = true; // One must be provided

    // A location code.
    cmp.types.v4.LocationCode location_code = 1;

    // Single geographic point represented by two double fields.
    cmp.types.v4.Coordinates location_coordinates = 2;
  }
}

enum TransportType {
  TRANSPORT_TYPE_UNSPECIFIED = 0; // Default/unspecified transport type
  TRANSPORT_TYPE_FLIGHT = 1; // Air transport via aircraft
  TRANSPORT_TYPE_TRAIN = 2; // Rail transport via train or railway
  TRANSPORT_TYPE_TRANSFER = 3; // Transfer services like shuttles or private cars
  TRANSPORT_TYPE_BUS = 4; // Road transport via bus or coach
}
