syntax = "proto3";

// ### Ping Message
package cmp.services.ping.v2;

import "buf/validate/validate.proto";
import "cmp/types/v4/common.proto";
import "google/protobuf/timestamp.proto";

// The ping message is designed to test the availability of a provider service and
// to test the network latency as in the gRPC metadata information the DateTime is
// stored of each hop.
message PingRequest {
  // Message Header
  cmp.types.v4.RequestHeader header = 1 [(buf.validate.field).required = true];

  // Ping message
  string message = 2 [(buf.validate.field).string.max_bytes = 512];

  // DateTime of the ping request
  //
  // Timestamps may be used for both off-chain and on-chain operations.
  // For on-chain operations, only seconds are supported, and nanoseconds
  // will be ignored.
  google.protobuf.Timestamp timestamp = 3 [(buf.validate.field).required = true];
}

message PingSuccessResponse {
  // Message Header
  cmp.types.v4.SuccessResponseHeader header = 1 [(buf.validate.field).required = true];

  // Ping message
  string message = 2 [(buf.validate.field).string.max_bytes = 512];

  // DateTime of the ping response
  //
  // Timestamps may be used for both off-chain and on-chain operations.
  // For on-chain operations, only seconds are supported, and nanoseconds
  // will be ignored.
  google.protobuf.Timestamp timestamp = 3 [(buf.validate.field).required = true];
}

message PingErrorResponse {
  // Common error response header used in every error response.
  cmp.types.v4.ErrorResponseHeader header = 1 [(buf.validate.field).required = true];
}

message PingResponse {
  oneof response {
    option (buf.validate.oneof).required = true; // One must be provided
    cmp.services.ping.v2.PingSuccessResponse success_response = 1;
    cmp.services.ping.v2.PingErrorResponse error_response = 2;
  }
}

// The Ping Service definition
//
// ![Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/ping/v2/ping.proto.dot.xs.svg)
//
// [Open Message Diagram](https://storage.googleapis.com/docs-cmp-files/diagrams/proto/cmp/services/ping/v2/ping.proto.dot.svg)
//
/// @custom:cmp-service type:core routing:p2p on-chain:false
service PingService {
  // Ping Method
  rpc Ping(PingRequest) returns (PingResponse);
}
