syntax = "proto3";

package cmp.services.carbon.v1;

import "cmp/services/carbon/v1/search_query_types.proto";
import "cmp/types/v1/common.proto";
import "cmp/types/v3/search.proto";

message CarbonCompensateSearchRequest {
  // Message header. Contains API version, message info string and end-user wallet
  // address
  cmp.types.v1.RequestHeader header = 1;

  // Search request metadata
  cmp.types.v3.SearchRequestMetadata metadata = 2;

  // Generic search parameters Ex: Inclusion of OnRequest options and inclusion of
  // only the cheapest or all options.
  // In the search parameters multiple filters can be applied for upfront filtering
  // of the search results to for example to only include hotels that are less than
  // one kilometer from the beach, have a kids club and offer an a la carte restaurant
  cmp.types.v3.SearchParameters search_parameters_generic = 3;

  repeated cmp.services.carbon.v1.CarbonSearchQuery queries = 4;
}

message CarbonCompensateSearchResponse {
  // Message header. Contains API version, message info string and end user wallet
  // address.
  cmp.types.v1.ResponseHeader header = 1;

  // Search response metadata
  cmp.types.v3.SearchResponseMetadata metadata = 2;
}

// Service
service CarbonCompensateService {
  rpc CarbonCompensateSearch(CarbonCompensateSearchRequest) returns (CarbonCompensateSearchResponse);
}
