name: buf

on:
  push:
    # Only run when there are changes under proto dir
    paths:
      - "proto/**"
  pull_request:
    # Only run when there are changes under proto dir
    paths:
      - "proto/**"

jobs:
  # Run buf's lint to check for errros
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
  # Push the draft branch to buf.build
  bsr-push-draft:
    runs-on: ubuntu-latest
    needs: buf-lint
    if: github.ref == 'refs/heads/draft'
    environment: draft
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "proto"
          draft: true
          buf_token: ${{ secrets.BUF_BSR_TOKEN }}
